### ISSUE TITLE
Poll intervall

### ISSUE THREAD

**Issue by DSorlov** [fredrikbaberg/ha-sensor-sl#19]
Should be able to specify intervalls for polling the api due to restrictions, this in contrast to using a binary sensor which could also be usefull

**Comment by fredrikbaberg** [comment]
I've attempted to reduce number of API calls through gathering them by station ID, but never got to specifying poll interval.

Instead I looked at having a binary sensor which would enable/disable polling completely. In 0.81.0 `homeassistant.update_entity`was introduced, which may (or may not) be useful.

**Comment by fredrikbaberg** [comment]
As this repository is being archived, I'm closing the issue.
