### ISSUE TITLE
Showing incorrect lines

### ISSUE THREAD

**Issue by theGurk** [fredrikbaberg/ha-sensor-sl#23]
If you choose Odenplan as station and then add line 43 (which is the "Pendel-tåg") you will also get line 4 (the bus) even thou you haven´t stated that. Do you have any fix for this? See attached files that you can see that it shows that next line is number 4 but I have not stated that line in the setup

![setup](https://user-images.githubusercontent.com/24705494/53198100-e675af80-361b-11e9-9247-0cd7e608eaf2.PNG)
![line43](https://user-images.githubusercontent.com/24705494/53198103-e675af80-361b-11e9-8fd6-d0d1767b1f2d.PNG)

**Comment by fredrikbaberg** [comment]
I'm afraid I don't have any suggestions for that. As I'm not currently developing this, I'm archiving the repository. I suggest you have a look at the following repository instead, which has been more active: https://github.com/DSorlov/ha-sensor-sl

**Comment by fredrikbaberg** [comment]
As this repository is being archived, I'm closing the issue.
